# Generated by Django 3.2.5 on 2022-09-01 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account_id_email', serialize=False, to='user.newuser')),
                ('message_name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('message_email', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('message_body', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(blank=True, max_length=60, null=True)),
                ('exercise_description', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('account_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='user.newuser')),
                ('in_challenge', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workout_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('workout_description', models.CharField(blank=True, max_length=150, null=True)),
                ('goal', models.CharField(blank=True, choices=[('CONSISTENCY', 'Consistency'), ('PROGRESSION', 'Progression'), ('TONNAGE', 'Tonnage')], max_length=20)),
                ('unique_str', models.CharField(blank=True, max_length=150, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_workout', related_query_name='user_workout', to='gym.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', related_query_name='exercises', to='gym.exercises')),
                ('workout_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_workout_session', related_query_name='user_workout_session', to='gym.workout')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(blank=True, default=0, null=True)),
                ('weights', models.IntegerField(blank=True, default=0, null=True)),
                ('exercise_sets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercise_set', related_query_name='workout_exercise_set', to='gym.workoutexercisesession')),
            ],
        ),
    ]
