# Generated by Django 3.2.5 on 2022-08-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
