# Generated by Django 3.2.5 on 2022-08-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercisesession',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutexercisesession',
            name='date_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
