# Generated by Django 3.2.5 on 2022-08-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='exercise_description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='userworkout',
            name='user_workout_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
