# Generated by Django 3.2.5 on 2022-09-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='message_body',
            field=models.CharField(default='testing', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='message_email',
            field=models.CharField(default='test@test.com', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='message_name',
            field=models.CharField(default='test', max_length=200, null=True),
        ),
    ]
