# Generated by Django 3.2.5 on 2022-08-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='account_id',
        ),
    ]
