# Generated by Django 3.2.5 on 2022-09-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='message_body',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='message_email',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='message_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
