# Generated by Django 3.2.5 on 2022-08-31 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_workoutexercisesession_workout_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercisesession',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', related_query_name='exercises', to='gym.exercises'),
        ),
    ]
